import pyxel


SPRITE_LETTERS = {
    ".": "0", "H": "8", "W": "7", "G": "6", "B": "c",
    "L": "6", "C": "1", "S": "7", "J": "9", "K": "0", "N": "5", "D": "e", "M": "c",
}
SPRITE_ROWS = (
    "......WGWG......",
    ".....WGWHH......",
    ".....WGWGHG.....",
    ".....WGWHWWH....",
    "......W.HH......",
    ".CCWBBBBBLL.....",
    ".CCBBBBBBLLB....",
    ".CC.BBBBLL.B....",
    ".CC.BBBBLL.B....",
    ".CC.BBBBLL.B....",
    ".CC.SBBLL..S....",
    "....BB.BB.......",
    "....BB.BB.......",
    "...SS...SS......",
    "................",
    "................",
)
FRONT_ROWS = (
    ".....WWWWWW.....",
    "....WWWWWWWW....",
    "....WHHHHHHW....",
    "....HHHHHHHH....",
    "....HKHHHHKH....",
    "....HHHHHHHH....",
    ".....WWWWWW.....",
    ".....WWWWWW.....",
    "...BBBBBBBBBB...",
    "..SBBBBBBBBBBS..",
    "..SBBBBBBBBBBS..",
    "....BBBBBBBB....",
    "....BGGGGGGB....",
    "....BB....BB....",
    "....BB....BB....",
    "...SS......SS...",
)
BACK_ROWS = (
    ".....WWWWWW.....",
    "....WWWWWWWW....",
    "....WWWWWWWW....",
    "....WWWWWWWW....",
    "....WWWWWWWW....",
    ".....WWWWWW.....",
    "...BBBBBBBBBB...",
    "..SBBBBWGBBBBS..",
    "..SBBBBGWBBBBS..",
    "..SBBBBWGBBBBS..",
    "...BBBBGWBBBB...",
    "....BBBBBBBB....",
    "....BBBBBBBB....",
    "....BB....BB....",
    "....BB....BB....",
    "...SS......SS...",
)
PORTRAIT_FRONT_ROWS = (
    "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
    "NNNNNNNNNNNKKKKKKKKKKNNNNNNNNNNN",
    "NNNNNNNNNNKWGGWWGGWWGKNNNNNNNNNN",
    "NNNNNNNNNNKWGWGGWGWWGKNNNNNNNNNN",
    "NNNNNNNNNNKWWGGWWGGWWKNNNNNNNNNN",
    "NNNNNNNNNNKWWHHHHHHWWKNNNNNNNNNN",
    "NNNNNNNNNKWWHHHHHHHHWWKNNNNNNNNN",
    "NNNNNNNNNKHHHHHHHHHHHHHHKNNNNNNN",
    "NNNNNNNNNKHHKKHHHHHHKKHHKNNNNNNN",
    "NNNNNNNNNKHHHHHHHHHHHHHHKNNNNNNN",
    "NNNNNNNNNKHHHHHJJJHHHHHHKNNNNNNN",
    "NNNNNNNNNKHHHHHJJJHHHHHHKNNNNNNN",
    "NNNNNNNNNKKWWWWWWWWWWWWKKNNNNNNN",
    "NNNNNNNNNKWWGGWWWWWWGGWWKNNNNNNN",
    "NNNNNNNNNKWGGWWWWWWWWGGWKNNNNNNN",
    "NNNNNNNNNKWGGWWWWWWWWGGWKNNNNNNN",
    "NNNNNNNNNNKWGGWWWWWWGGWKNNNNNNNN",
    "NNNNNNNNNNKWGGWWWWWWGGWKNNNNNNNN",
    "NNNNNNNNNNNKWWWWWWWWWWKNNNNNNNNN",
    "NNNNNNNNNNNKWWWWWWWWWWKNNNNNNNNN",
    "NNNNNNNNNNNNKWWWWWWWWKNNNNNNNNNN",
    "NNNNNNNNNNNNNKWWWWWWKNNNNNNNNNNN",
    "NNNNNNNNNNNNNNKHHHHKNNNNNNNNNNNN",
    "NNNNNNNBBBBKHHHHHHHHKBBBBNNNNNNN",
    "NNNNNBBBBBBKHHHHHHHHKBBBBBBNNNNN",
    "NNNNBBBBBBBBBBKKKKBBBBBBBBBBNNNN",
    "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
    "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
)

PORTRAIT_BACK_ROWS = (
    "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
    "NNNNNNNNNNNKKKKKKKKKKNNNNNNNNNNN",
    "NNNNNNNNNNKWGGWWGGWWGKNNNNNNNNNN",
    "NNNNNNNNNNKWGWGGWGWWGKNNNNNNNNNN",
    "NNNNNNNNNNKWWGGWWGGWWKNNNNNNNNNN",
    "NNNNNNNNNNKWWWWWWWWWWKNNNNNNNNNN",
    "NNNNNNNNNKWWWWWWWWWWWWWKNNNNNNNN",
    "NNNNNNNNNKWWWWWWWWWWWWWWKNNNNNNN",
    "NNNNNNNNNKWWWWWGWWGWWWWWKNNNNNNN",
    "NNNNNNNNNKWWWWWGGGGWWWWWKNNNNNNN",
    "NNNNNNNNNKWWWWWGWWGWWWWWKNNNNNNN",
    "NNNNNNNNNKWWWWWGGGGWWWWWKNNNNNNN",
    "NNNNNNNNNKWWWWWWGGWWWWWWKNNNNNNN",
    "NNNNNNNNNKHHHHHGWWGHHHHHKNNNNNNN",
    "NNNNNNNNNKHHHHHGWWGHHHHHKNNNNNNN",
    "NNNNNNNNNKHHHHHGGGGHHHHHKNNNNNNN",
    "NNNNNNNNNKHHHHHGWWGHHHHHKNNNNNNN",
    "NNNNNNNNNKKHHHHGWWGHHHHKKKNNNNNN",
    "NNNNNNNNNNNKHHHWWWWHHHKNNNNNNNNN",
    "NNNNNNNBBBBKHHWWWWHHKBBBBNNNNNNN",
    "NNNNNBBBBBBKHHWWWWHHKBBBBBBNNNNN",
    "NNNNBBBBBBBBKWWWWKBBBBBBBBNNNNNN",
    "NNNNNBBBBBBBBBBKKKBBBBBBBBBBNNNN",
    "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
    "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
)

PORTRAIT_ROWS = (
    "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
    "NNNNNNNNNNNNNNKKKKKKKKKKNNNNNNNN",
    "NNNNNNNNNNNNNNKWGGWWGGWWKNNNNNNN",
    "NNNNNNNNNNNNNKKWGWGGWGGWWKKNNNNN",
    "NNNNNNNNNNNNNKKGGWWGGWGGWKKNNNNN",
    "NNNNNNNNNNNNNKKKHHHHHHHHHHHKNNNN",
    "NNNNNNNNNNNNKHHHHHHJHHJHHHHHHKNN",
    "NNNNNNNNNNNKHHHHHHHHHJHHHHHHHKNN",
    "NNNNNNNNNNNKHHHHHHHHKKKKKKKKKNNN",
    "NNNNNNNNNNKHHHHHHHHHHHHHKWHKNNNN",
    "NNNNNNNNNNKHHHHHHHHHHHHHKWHKNNNN",
    "NNNNNNNNNKKHHHHHHHHHHHHHHHHKKNNN",
    "NNNNNNNNNKKHHHHHHHHHHHHHHHHHHKNN",
    "NNNNNNNNNKKHHHHGGKGGWWWWWWWKKNNN",
    "NNNNNNNNNKKKHHGGGGGWGWGWGWWKKNNN",
    "NNNNNNNNNKKKHHHGWWGWGWGWGWGKKNNN",
"NNNNNNNNNKKKHHHGWGWGWGWGWGWKKNNN",
    "NNNNNNNNNKKKHHHGWGWGWGWGWGWKKNNN",
    "NNNNNNNNNKKKHHHWWGWWWGWWWGKKKKNN",
    "NNNNNNNNNKKKKHHHWWWWWWWWWKKNNNNN",
    "NNNNNNNNNKKKHHHHHHHHHHHHKKKNNNNN",
    "NNNNNNNNNKKKKHHHHHHHHHHHKKKNNNNN",
    "NNNNNNNNNKKKHHHHHHHHHHHKKKNNNNNN",
    "NNNNNNNNNNKKHHHHHHHHHHKKNNNNNNNN",
    "NNNNNNNNNNNKKKKKKKKKKKKKNNNNNNNN",
    "NNNNNNNNKKKKKKKKKKKKKKKKNNNNNNNN",
    "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
    "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
)
SPRITE_CHARS = tuple(
    "".join(SPRITE_LETTERS[ch] for ch in row) for row in SPRITE_ROWS
)
FRONT_CHARS = tuple("".join(SPRITE_LETTERS[ch] for ch in row) for row in FRONT_ROWS)
BACK_CHARS = tuple("".join(SPRITE_LETTERS[ch] for ch in row) for row in BACK_ROWS)
PORTRAIT_CHARS = tuple(
    "".join("0123456789abcdef"[int(SPRITE_LETTERS[ch], 16)] for ch in row)
    for row in PORTRAIT_ROWS
)
PORTRAIT_FRONT_CHARS = tuple(
    "".join("0123456789abcdef"[int(SPRITE_LETTERS[ch], 16)] for ch in row)
    for row in PORTRAIT_FRONT_ROWS
)
PORTRAIT_BACK_CHARS = tuple(
    "".join("0123456789abcdef"[int(SPRITE_LETTERS[ch], 16)] for ch in row)
    for row in PORTRAIT_BACK_ROWS
)


def load_banks():
    pyxel.images[0].set(0, 0, SPRITE_CHARS)
    pyxel.images[0].set(16, 0, FRONT_CHARS)
    pyxel.images[0].set(0, 16, BACK_CHARS)
    pyxel.images[0].set(32, 0, PORTRAIT_CHARS)
    pyxel.images[0].set(64, 0, PORTRAIT_FRONT_CHARS)
    pyxel.images[0].set(96, 0, PORTRAIT_BACK_CHARS)
