import pyxel

from eggrim.fog import nearest_fog_palette, palette_rgb

SPRITE_LETTERS = {
    ".": "0", "H": "8", "W": "7", "G": "6", "B": "c",
    "L": "6", "C": "1", "S": "7", "J": "9", "K": "0", "N": "5", "D": "e", "M": "c",
    "E": "d", "F": "5",
}

PORTRAIT_FRONT_ROWS = (
"NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
"NNNNNNNNNNNNKWGGKKGKNNNNNNNNNNNN",
"NNNNNNNNNNNKWWGGKKGGKNNNNNNNNNNN",
"NNNNNNNNNNNKWWWGGKKGGKNNNNNNNNNN",
"NNNNNNNNNNNKWWWGGKKGGKNNNNNNNNNN",
"NNNNNNNNNNKWGGHHHHHHHHGGWKNNNNNN",
"NNNNNNNNNKWGHKHHHHHHHKHGWKNNNNNN",
"NNNNNNNNNKWGHKHHHHHHHKHGWKNNNNNN",
"NNNNNNNNNKWGHKHHHHHHHKHGWKNNNNNN",
"NNNNNNNNNKWGHHHHHHHHHHGWKNNNNNNN",
"NNNNNNNNNKWGHHJJJJJJHHGWKNNNNNNN",
"NNNNNNNNNKWGHJJJJJJJHHWGKNNNNNNN",
"NNNNNNNNNKWGWWWWWWWWWWGWKNNNNNNN",
"NNNNNNNNNKWGGWGWGWGWGWGWKNNNNNNN",
"NNNNNNNNNKWGGWGWWGWWGWWGKNNNNNNN",
"NNNNNNNNNKWGGWGWGWGWGWGWKNNNNNNN",
"NNNNNNNNNKWGGGWWGWWGWWGGKNNNNNNN",
"NNNNNNNNNKWGGGWWGWWGWWGGKNNNNNNN",
"NNNNNNNNNKWGGHHHHHHHHHGWKNNNNNNN",
"NNNNNNNNNNWGHHHHHHHHHHGWKNNNNNNN",
"NNNNNNNNNNNWGHHHHHHHHGWKNNNNNNNN",
"NNNNNNNNNNNNWGHHHHHHGWKNNNNNNNNN",
"NNNNNNNNNNNNNWGHHHHGWKNNNNNNNNNN",
"NNNNNNNBBBBKWGHHHHHWGKBBBBNNNNNN",
"NNNNNNBBBBKWGGHHHHHHGGWKBBBBNNNN",
"NNNNBBBBBBBBBBKKKKBBBBBBBBBBNNNN",
"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
)

PORTRAIT_BACK_ROWS = (
"NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
"NNNNNNNNNNNNKWGGKKGKNNNNNNNNNNNN",
"NNNNNNNNNNNKWWGGKKGGKNNNNNNNNNNN",
"NNNNNNNNNNNKWWWGGKKGGKNNNNNNNNNN",
"NNNNNNNNNNNKWWWGGKKGGKNNNNNNNNNN",
"NNNNNNNNNNKWGGWGGKWGGWGGWKNNNNNN",
"NNNNNNNNNKWGGWGWWGGWWGGWGWKNNNNN",
"NNNNNNNNNKWGGWGWWGGWWGGWGWKNNNNN",
"NNNNNNNNNKWGGWWGGWWGGWWGGWKNNNNN",
"NNNNNNNNNKWGGWWGGWWGGWWGGWKNNNNN",
"NNNNNNNNNKWGWWGGWWGGWWGGWGWKNNNN",
"NNNNNNNNNNWGGWWGGWWGGWWGGWKNNNNN",
"NNNNNNNNNNWGWWGGWWGGWWGGWGKNNNNN",
"NNNNNNNNNNNWGGWWGGWWGGWWGKNNNNNN",
"NNNNNNNNNNNWGWWGGWWGGWWGKNNNNNNN",
"NNNNNNNNNNNNGWWGGWWGGWWGKNNNNNNN",
"NNNNNNNNNNNNNWGGWWGGWWGKNNNNNNNN",
"NNNNNNNNNNNNNNWGWWGGWWKNNNNNNNNN",
"NNNNNNNNNNNNNNWGGWWGGWKNNNNNNNNN",
"NNNNNNNNNNNNNNNWGGWWGGKNNNNNNNNN",
"NNNNNNNNNNNNNNNNWGWWGGKNNNNNNNNN",
"NNNNNNNNNNNNNNNNWGGWGKNNNNNNNNNN",
"NNNNNNNNNNNNNNNNWWGGWKNNNNNNNNNN",
"NNNNNNNBBBBBBKWGWWWGGWKBBBBBBNNN",
"NNNNNNBBBBBBKWGGWWGGWGKBBBBBBNNN",
"NNNNBBBBBBBBBBKKKKBBBBBBBBBBNNNN",
"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
)

PORTRAIT_ROWS = (
    "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
    "NNNNNNNNNNNNNNKWGGKKGKNNNNNNNNNN",
    "NNNNNNNNNNNNNKWWGGKKGGWKNNNNNNNN",
    "NNNNNNNNNNNNKWWWGGKKGGWWKNNNNNNN",
    "NNNNNNNNNNNNKWWWGGKKGGWWKNNNNNNN",
    "NNNNNNNNNNNKWWGGHHHHHHHHKNNNNNNN",
    "NNNNNNNNNNKWWGGHKHHHHHHHHKNNNNNN",
    "NNNNNNNNNNKWWGGHKHHHHHHHHKNNNNNN",
    "NNNNNNNNNKWWGGHKKHHHHHHHHKNNNNNN",
    "NNNNNNNNNKWWGGWWHHHHHHHHHKNNNNNN",
    "NNNNNNNNNKWWGGWHHJJJJHHHHKNNNNNN",
    "NNNNNNNNNKWWGGWHHJJJJHHHHKNNNNNN",
    "NNNNNNNNNKWWGGWWWWWWWWWWWKNNNNNN",
    "NNNNNNNNNKWWGGWGWGWGWGWGWKNNNNNN",
    "NNNNNNNNNKWWGGWGWWGWWGWWGKNNNNNN",
    "NNNNNNNNNKWWGGWGWGWGWGWGWKNNNNNN",
    "NNNNNNNNNKWWGGWGWWGWWGWWGKNNNNNN",
    "NNNNNNNNNKWWGGWGWWGWWGWWGKNNNNNN",
    "NNNNNNNNNKKWGGHHHHHHHHHHKNNNNNNN",
    "NNNNNNNNNKKWWGHHHHHHHHHKNNNNNNNN",
    "NNNNNNNNNKKWWGGHHHHHHHKNNNNNNNNN",
    "NNNNNNNNNKKKWWGGHHHHHKNNNNNNNNNN",
    "NNNNNNNNNKKKKWWGGHHHKNNNNNNNNNNN",
    "NNNNNNNNNKKKKKWWGGHKNNNNNNNNNNNN",
    "NNNNNNNNNKKKKKKWWGKKNNNNNNNNNNNN",
    "NNNNNNNNNNKKKKKKKKKKKKNNNNNNNNNN",
    "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
    "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
)

PORTRAIT_CHARS = tuple(
    "".join("0123456789abcdef"[int(SPRITE_LETTERS[ch], 16)] for ch in row)
    for row in PORTRAIT_ROWS
)
PORTRAIT_FRONT_CHARS = tuple(
    "".join("0123456789abcdef"[int(SPRITE_LETTERS[ch], 16)] for ch in row)
    for row in PORTRAIT_FRONT_ROWS
)
PORTRAIT_BACK_CHARS = tuple(
    "".join("0123456789abcdef"[int(SPRITE_LETTERS[ch], 16)] for ch in row)
    for row in PORTRAIT_BACK_ROWS
)


PORTRAIT_KEYS = ("side", "front", "back")
PORTRAIT_SRC = {"side": (32, 0), "front": (64, 0), "back": (96, 0)}
PORTRAIT_BLEND_STEPS = ((1, 1 / 3), (2, 2 / 3))
PORTRAIT_BLEND_POS = {}
PORTRAIT_BLEND_ROW = 64


def render_portrait_blends():
    src = pyxel.images[0]
    grids = {}
    for key in PORTRAIT_KEYS:
        x0, y0 = PORTRAIT_SRC[key]
        grids[key] = [[src.pget(x0 + x, y) for x in range(32)] for y in range(32)]
    slot_index = 0
    for a in PORTRAIT_KEYS:
        for b in PORTRAIT_KEYS:
            if a == b:
                continue
            for step_index, alpha in PORTRAIT_BLEND_STEPS:
                rows = []
                for y in range(32):
                    chars = []
                    for x in range(32):
                        rgb_a = palette_rgb(pyxel.colors[grids[a][y][x]])
                        rgb_b = palette_rgb(pyxel.colors[grids[b][y][x]])
                        rgb = tuple(
                            rgb_a[i] * (1 - alpha) + rgb_b[i] * alpha for i in range(3)
                        )
                        chars.append("0123456789abcdef"[nearest_fog_palette(rgb)])
                    rows.append("".join(chars))
                if slot_index < 8:
                    u, v = 32 * slot_index, PORTRAIT_BLEND_ROW
                else:
                    u, v = 32 * (slot_index - 8), PORTRAIT_BLEND_ROW + 32
                PORTRAIT_BLEND_POS[(a, b, step_index)] = (u, v)
                pyxel.images[0].set(u, v, rows)
                slot_index += 1